[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Justin Browne <jebdude89@gmail.com>"]
edition = "2021"

[dependencies]
permutohedron = "*"
num = "*"
ordered-float = "*"

[lints]
workspace = true
